spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    default-schema: users
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: ES256
          public-key-location: ${auth.public-key-location}

auth:
  access-token-ttl: 5m
  refresh-token-ttl: 30d
  refresh-cookie-secure: true
  private-key-location: classpath:keys/private.pem
  public-key-location: classpath:keys/public.pem
  key-id: user-service
server:
  port: 8080
