package com.cs3219.foc.user.infrastructure.storage;

import com.cs3219.foc.user.config.AvatarProperties;
import com.cs3219.foc.user.exception.AvatarException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Component;

@Component
public class LocalAvatarStorage implements AvatarStorage {
    private final Path directory;

    public LocalAvatarStorage(AvatarProperties properties) {
        this.directory = properties.directory().toAbsolutePath().normalize();
    }

    @Override
    public void write(String key, byte[] image) {
        var path = resolve(key);
        try {
            Files.createDirectories(directory);
            try (var output = Files.newOutputStream(
                    path, StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE, LinkOption.NOFOLLOW_LINKS)) {
                output.write(image);
            }
        } catch (IOException exception) {
            throw unavailable(exception);
        }
    }

    @Override
    public byte[] read(String key) {
        try (var input = Files.newInputStream(resolve(key), LinkOption.NOFOLLOW_LINKS)) {
            return input.readAllBytes();
        } catch (NoSuchFileException exception) {
            throw new AvatarException(HttpStatus.NOT_FOUND, "Avatar not found");
        } catch (IOException exception) {
            throw unavailable(exception);
        }
    }

    @Override
    public void delete(String key) {
        try {
            Files.deleteIfExists(resolve(key));
        } catch (IOException exception) {
            throw unavailable(exception);
        }
    }

    private Path resolve(String key) {
        // Keys are generated by the server. Never resolve uploaded filenames.
        if (key == null || !key.matches("[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\.png")) {
            throw new AvatarException(HttpStatus.SERVICE_UNAVAILABLE, "Invalid avatar storage reference");
        }
        return directory.resolve(key);
    }

    private AvatarException unavailable(IOException cause) {
        return new AvatarException(HttpStatus.SERVICE_UNAVAILABLE, "Avatar storage is unavailable", cause);
    }
}
