spring:
  application:
    name: credit-service
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    default-schema: users
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
          jws-algorithms: ES256
server:
  port: 8083